# Variables for Azure Development Environment

variable "resource_group_name" {
  description = "The name of the resource group"
  type        = string
  default     = "rg-myproject-dev"
}

variable "azure_resource_group" {
  description = "Azure resource group name (alias for resource_group_name)"
  type        = string
  default     = "rg-myproject-dev"
}

variable "location" {
  description = "The Azure region where resources will be created"
  type        = string
  default     = "brazilsouth"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "promata"
}

variable "vm_size" {
  description = "Size of the Azure VM (equivalent to AWS t2.medium)"
  type        = string
  default     = "Standard_B2ms"
}

variable "instance_count" {
  description = "Number of VM instances (1 for Compose, 2+ for Swarm)"
  type        = number
  default     = 2

  validation {
    condition     = var.instance_count >= 1
    error_message = "instance_count must be at least 1"
  }
}

# SSH keys are now auto-generated by Terraform

variable "storage_account_name" {
  description = "Name of the storage account (must be globally unique)"
  type        = string
  default     = "promatadevstg"

  validation {
    condition     = can(regex("^[a-z0-9]{3,24}$", var.storage_account_name))
    error_message = "Storage account name must be between 3 and 24 characters, lowercase letters and numbers only."
  }
}

variable "docker_compose_version" {
  description = "Docker Compose version to install"
  type        = string
  default     = "2.21.0"
}

variable "common_tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default = {
    Project     = "promata"
    Environment = "dev"
    ManagedBy   = "terraform"
    Owner       = "pro-mata-team"
  }
}

# Database configuration
variable "postgres_db" {
  description = "PostgreSQL database name"
  type        = string
  default     = "promata_dev"
}

variable "postgres_user" {
  description = "PostgreSQL username"
  type        = string
  default     = "promata"
}

# Application configuration
variable "domain_name" {
  description = "Domain name for the application"
  type        = string
  default     = "promata.com.br"
}

variable "backend_image" {
  description = "Backend Docker image"
  type        = string
  default     = "experimentanaturalmente/pro-mata-backend-dev:latest"
}

# variable "frontend_image" {
#   description = "Frontend Docker image"
#   type        = string
#   default     = "experimentanaturalmente/pro-mata-frontend-dev:latest"
# }

variable "backend_replicas" {
  description = "Number of backend service replicas"
  type        = number
  default     = 1
}

# variable "frontend_replicas" {
#   description = "Number of frontend service replicas"
#   type        = number
#   default     = 1
# }

# Cloudflare variables
variable "cloudflare_api_token" {
  description = "Cloudflare API Token with Zone:Read, DNS:Edit permissions"
  type        = string
  sensitive   = true
  default     = null
}

variable "cloudflare_zone_id" {
  description = "Cloudflare Zone ID for your domain"
  type        = string
  default     = null
}

variable "enable_cloudflare_dns" {
  description = "Enable Cloudflare DNS management"
  type        = bool
  default     = true
}

variable "create_page_rules" {
  description = "Whether to create page rules for optimization"
  type        = bool
  default     = false
}

variable "azure_location" {
  description = "Azure location (alias for location)"
  type        = string
  default     = "brazilsouth"
}

variable "monitoring_enabled" {
  description = "Enable monitoring and logging"
  type        = bool
  default     = true
}

variable "migration_image" {
  description = "Migration Docker image"
  type        = string
  default     = "experimentanaturalmente/pro-mata-database-dev:latest"
}

# Additional variables from .env configuration

variable "env_color" {
  description = "Environment color for UI differentiation"
  type        = string
  default     = "blue"
}

variable "env_prefix" {
  description = "Environment prefix"
  type        = string
  default     = "dev"
}

variable "subdomain_prefix" {
  description = "Subdomain prefix for the domain"
  type        = string
  default     = ""
}

variable "api_subdomain" {
  description = "API subdomain"
  type        = string
  default     = "api"
}

variable "admin_subdomain" {
  description = "Admin subdomain"
  type        = string
  default     = "admin"
}

variable "azure_subscription_id" {
  description = "Azure subscription ID"
  type        = string
  sensitive   = true
}

variable "database_image" {
  description = "Database Docker image"
  type        = string
  default     = "experimentanaturalmente/pro-mata-database-infrastructure:latest"
}

variable "app_version" {
  description = "Application version"
  type        = string
  default     = "latest"
}

variable "postgres_password" {
  description = "PostgreSQL password"
  type        = string
  sensitive   = true
  default     = "postgres"
}

variable "postgres_replica_user" {
  description = "PostgreSQL replication user"
  type        = string
  default     = "replicator"
}

variable "postgres_replica_password" {
  description = "PostgreSQL replication password"
  type        = string
  sensitive   = true
  default     = "postgres"
}

variable "database_size" {
  description = "Database size/tier"
  type        = string
  default     = "Basic"
}

variable "jwt_secret" {
  description = "JWT secret key"
  type        = string
  sensitive   = true
  default     = "your-super-secret-jwt-key"
}

variable "jwt_expires_in" {
  description = "JWT token expiration time"
  type        = string
  default     = "24h"
}

variable "pgbouncer_pool_mode" {
  description = "PgBouncer pool mode"
  type        = string
  default     = "session"
}

variable "pgbouncer_pool_size" {
  description = "PgBouncer pool size"
  type        = number
  default     = 20
}

variable "pgbouncer_max_client_conn" {
  description = "PgBouncer maximum client connections"
  type        = number
  default     = 100
}

variable "pgadmin_email" {
  description = "PgAdmin email"
  type        = string
  default     = "admin@promata.com.br"
}

variable "pgadmin_password" {
  description = "PgAdmin password"
  type        = string
  sensitive   = true
  default     = "pgadmin"
}

variable "traefik_log_level" {
  description = "Traefik log level"
  type        = string
  default     = "INFO"
}

variable "traefik_api_dashboard" {
  description = "Enable Traefik API dashboard"
  type        = bool
  default     = true
}

variable "traefik_auth_users" {
  description = "Traefik authentication users"
  type        = string
  sensitive   = true
  default     = "admin:$$2y$$10$$example_hash_change_this"
}

variable "acme_email" {
  description = "ACME email for SSL certificates"
  type        = string
  default     = "admin@promata.com.br"
}

variable "prometheus_retention" {
  description = "Prometheus data retention period"
  type        = string
  default     = "7d"
}

variable "grafana_admin_password" {
  description = "Grafana admin password"
  type        = string
  sensitive   = true
  default     = "grafana_dev_password_change_me"
}

variable "umami_api_key" {
  description = "Umami API key"
  type        = string
  default     = ""
}

variable "umami_db_password" {
  description = "Umami database password"
  type        = string
  sensitive   = true
  default     = "umami_dev_password_change_me"
}

variable "ssl_enabled" {
  description = "Enable SSL/TLS"
  type        = bool
  default     = true
}

variable "ssl_mode" {
  description = "SSL mode configuration"
  type        = string
  default     = "flexible"
}

variable "backup_enabled" {
  description = "Enable backup functionality"
  type        = bool
  default     = true
}

variable "backup_retention_days" {
  description = "Backup retention period in days"
  type        = number
  default     = 7
}

variable "server_public_ip" {
  description = "Server public IP address"
  type        = string
  default     = "0.0.0.0"
}

variable "create_dns_records" {
  description = "Whether to create DNS records"
  type        = bool
  default     = true
}

# Additional variables from CI/CD configuration
variable "database_base_image" {
  description = "Database base image"
  type        = string
  default     = "experimentanaturalmente/pro-mata-database-dev:latest"
}

variable "database_infrastructure_image" {
  description = "Database infrastructure image"
  type        = string
  default     = "experimentanaturalmente/pro-mata-database-infrastructure:latest"
}

variable "umami_website_id" {
  description = "Umami website ID"
  type        = string
  default     = "dev-website-id"
}

variable "umami_hash_salt" {
  description = "Umami hash salt"
  type        = string
  sensitive   = true
  default     = "default-salt"
}

variable "enable_analytics" {
  description = "Enable analytics tracking"
  type        = bool
  default     = true
}